/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthAuthorizeRouteImport } from './routes/auth/authorize'
import { Route as formFIdRouteImport } from './routes/(form)/f/$id'
import { Route as WorkspaceWorkspaceIdDashboardRouteRouteImport } from './routes/workspace/$workspaceId/_dashboard/route'
import { Route as WorkspaceWorkspaceIdDashboardIndexRouteImport } from './routes/workspace/$workspaceId/_dashboard/index'
import { Route as WorkspaceWorkspaceIdFormsIdPreviewIndexRouteImport } from './routes/workspace/$workspaceId/forms/$id/preview/index'
import { Route as WorkspaceWorkspaceIdFormsIdEditIndexRouteImport } from './routes/workspace/$workspaceId/forms/$id/edit/index'

const WorkspaceWorkspaceIdRouteImport = createFileRoute(
  '/workspace/$workspaceId',
)()

const WorkspaceWorkspaceIdRoute = WorkspaceWorkspaceIdRouteImport.update({
  id: '/workspace/$workspaceId',
  path: '/workspace/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthorizeRoute = AuthAuthorizeRouteImport.update({
  id: '/auth/authorize',
  path: '/auth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const formFIdRoute = formFIdRouteImport.update({
  id: '/(form)/f/$id',
  path: '/f/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkspaceIdDashboardRouteRoute =
  WorkspaceWorkspaceIdDashboardRouteRouteImport.update({
    id: '/_dashboard',
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)
const WorkspaceWorkspaceIdDashboardIndexRoute =
  WorkspaceWorkspaceIdDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceWorkspaceIdDashboardRouteRoute,
  } as any)
const WorkspaceWorkspaceIdFormsIdPreviewIndexRoute =
  WorkspaceWorkspaceIdFormsIdPreviewIndexRouteImport.update({
    id: '/forms/$id/preview/',
    path: '/forms/$id/preview/',
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)
const WorkspaceWorkspaceIdFormsIdEditIndexRoute =
  WorkspaceWorkspaceIdFormsIdEditIndexRouteImport.update({
    id: '/forms/$id/edit/',
    path: '/forms/$id/edit/',
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth/authorize': typeof AuthAuthorizeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth': typeof AuthIndexRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdDashboardRouteRouteWithChildren
  '/f/$id': typeof formFIdRoute
  '/workspace/$workspaceId/': typeof WorkspaceWorkspaceIdDashboardIndexRoute
  '/workspace/$workspaceId/forms/$id/edit': typeof WorkspaceWorkspaceIdFormsIdEditIndexRoute
  '/workspace/$workspaceId/forms/$id/preview': typeof WorkspaceWorkspaceIdFormsIdPreviewIndexRoute
}
export interface FileRoutesByTo {
  '/auth/authorize': typeof AuthAuthorizeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth': typeof AuthIndexRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdDashboardIndexRoute
  '/f/$id': typeof formFIdRoute
  '/workspace/$workspaceId/forms/$id/edit': typeof WorkspaceWorkspaceIdFormsIdEditIndexRoute
  '/workspace/$workspaceId/forms/$id/preview': typeof WorkspaceWorkspaceIdFormsIdPreviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth/authorize': typeof AuthAuthorizeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/': typeof AuthIndexRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRouteWithChildren
  '/workspace/$workspaceId/_dashboard': typeof WorkspaceWorkspaceIdDashboardRouteRouteWithChildren
  '/(form)/f/$id': typeof formFIdRoute
  '/workspace/$workspaceId/_dashboard/': typeof WorkspaceWorkspaceIdDashboardIndexRoute
  '/workspace/$workspaceId/forms/$id/edit/': typeof WorkspaceWorkspaceIdFormsIdEditIndexRoute
  '/workspace/$workspaceId/forms/$id/preview/': typeof WorkspaceWorkspaceIdFormsIdPreviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth/authorize'
    | '/auth/callback'
    | '/auth'
    | '/workspace/$workspaceId'
    | '/f/$id'
    | '/workspace/$workspaceId/'
    | '/workspace/$workspaceId/forms/$id/edit'
    | '/workspace/$workspaceId/forms/$id/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/authorize'
    | '/auth/callback'
    | '/auth'
    | '/workspace/$workspaceId'
    | '/f/$id'
    | '/workspace/$workspaceId/forms/$id/edit'
    | '/workspace/$workspaceId/forms/$id/preview'
  id:
    | '__root__'
    | '/auth/authorize'
    | '/auth/callback'
    | '/auth/'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/_dashboard'
    | '/(form)/f/$id'
    | '/workspace/$workspaceId/_dashboard/'
    | '/workspace/$workspaceId/forms/$id/edit/'
    | '/workspace/$workspaceId/forms/$id/preview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthAuthorizeRoute: typeof AuthAuthorizeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthIndexRoute: typeof AuthIndexRoute
  WorkspaceWorkspaceIdRoute: typeof WorkspaceWorkspaceIdRouteWithChildren
  formFIdRoute: typeof formFIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace/$workspaceId': {
      id: '/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/authorize': {
      id: '/auth/authorize'
      path: '/auth/authorize'
      fullPath: '/auth/authorize'
      preLoaderRoute: typeof AuthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(form)/f/$id': {
      id: '/(form)/f/$id'
      path: '/f/$id'
      fullPath: '/f/$id'
      preLoaderRoute: typeof formFIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$workspaceId/_dashboard': {
      id: '/workspace/$workspaceId/_dashboard'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdDashboardRouteRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRoute
    }
    '/workspace/$workspaceId/_dashboard/': {
      id: '/workspace/$workspaceId/_dashboard/'
      path: '/'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof WorkspaceWorkspaceIdDashboardIndexRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdDashboardRouteRoute
    }
    '/workspace/$workspaceId/forms/$id/preview/': {
      id: '/workspace/$workspaceId/forms/$id/preview/'
      path: '/forms/$id/preview'
      fullPath: '/workspace/$workspaceId/forms/$id/preview'
      preLoaderRoute: typeof WorkspaceWorkspaceIdFormsIdPreviewIndexRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRoute
    }
    '/workspace/$workspaceId/forms/$id/edit/': {
      id: '/workspace/$workspaceId/forms/$id/edit/'
      path: '/forms/$id/edit'
      fullPath: '/workspace/$workspaceId/forms/$id/edit'
      preLoaderRoute: typeof WorkspaceWorkspaceIdFormsIdEditIndexRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRoute
    }
  }
}

interface WorkspaceWorkspaceIdDashboardRouteRouteChildren {
  WorkspaceWorkspaceIdDashboardIndexRoute: typeof WorkspaceWorkspaceIdDashboardIndexRoute
}

const WorkspaceWorkspaceIdDashboardRouteRouteChildren: WorkspaceWorkspaceIdDashboardRouteRouteChildren =
  {
    WorkspaceWorkspaceIdDashboardIndexRoute:
      WorkspaceWorkspaceIdDashboardIndexRoute,
  }

const WorkspaceWorkspaceIdDashboardRouteRouteWithChildren =
  WorkspaceWorkspaceIdDashboardRouteRoute._addFileChildren(
    WorkspaceWorkspaceIdDashboardRouteRouteChildren,
  )

interface WorkspaceWorkspaceIdRouteChildren {
  WorkspaceWorkspaceIdDashboardRouteRoute: typeof WorkspaceWorkspaceIdDashboardRouteRouteWithChildren
  WorkspaceWorkspaceIdFormsIdEditIndexRoute: typeof WorkspaceWorkspaceIdFormsIdEditIndexRoute
  WorkspaceWorkspaceIdFormsIdPreviewIndexRoute: typeof WorkspaceWorkspaceIdFormsIdPreviewIndexRoute
}

const WorkspaceWorkspaceIdRouteChildren: WorkspaceWorkspaceIdRouteChildren = {
  WorkspaceWorkspaceIdDashboardRouteRoute:
    WorkspaceWorkspaceIdDashboardRouteRouteWithChildren,
  WorkspaceWorkspaceIdFormsIdEditIndexRoute:
    WorkspaceWorkspaceIdFormsIdEditIndexRoute,
  WorkspaceWorkspaceIdFormsIdPreviewIndexRoute:
    WorkspaceWorkspaceIdFormsIdPreviewIndexRoute,
}

const WorkspaceWorkspaceIdRouteWithChildren =
  WorkspaceWorkspaceIdRoute._addFileChildren(WorkspaceWorkspaceIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthAuthorizeRoute: AuthAuthorizeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthIndexRoute: AuthIndexRoute,
  WorkspaceWorkspaceIdRoute: WorkspaceWorkspaceIdRouteWithChildren,
  formFIdRoute: formFIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
