/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthAuthorizeRouteImport } from './routes/auth/authorize'
import { Route as funnelFIdRouteImport } from './routes/(funnel)/f/$id'
import { Route as WorkspaceWorkspaceIdDashboardRouteRouteImport } from './routes/workspace/$workspaceId/_dashboard/route'
import { Route as WorkspaceWorkspaceIdDashboardIndexRouteImport } from './routes/workspace/$workspaceId/_dashboard/index'
import { Route as WorkspaceWorkspaceIdFunnelsIdPreviewIndexRouteImport } from './routes/workspace/$workspaceId/funnels/$id/preview/index'
import { Route as WorkspaceWorkspaceIdFunnelsIdEditIndexRouteImport } from './routes/workspace/$workspaceId/funnels/$id/edit/index'

const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthorizeRoute = AuthAuthorizeRouteImport.update({
  id: '/auth/authorize',
  path: '/auth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const funnelFIdRoute = funnelFIdRouteImport.update({
  id: '/(funnel)/f/$id',
  path: '/f/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkspaceIdDashboardRouteRoute =
  WorkspaceWorkspaceIdDashboardRouteRouteImport.update({
    id: '/_dashboard',
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)
const WorkspaceWorkspaceIdDashboardIndexRoute =
  WorkspaceWorkspaceIdDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceWorkspaceIdDashboardRouteRoute,
  } as any)
const WorkspaceWorkspaceIdFunnelsIdPreviewIndexRoute =
  WorkspaceWorkspaceIdFunnelsIdPreviewIndexRouteImport.update({
    id: '/workspace/$workspaceId/funnels/$id/preview/',
    path: '/workspace/$workspaceId/funnels/$id/preview/',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspaceWorkspaceIdFunnelsIdEditIndexRoute =
  WorkspaceWorkspaceIdFunnelsIdEditIndexRouteImport.update({
    id: '/workspace/$workspaceId/funnels/$id/edit/',
    path: '/workspace/$workspaceId/funnels/$id/edit/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/auth/authorize': typeof AuthAuthorizeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth': typeof AuthIndexRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdDashboardRouteRouteWithChildren
  '/f/$id': typeof funnelFIdRoute
  '/workspace/$workspaceId/': typeof WorkspaceWorkspaceIdDashboardIndexRoute
  '/workspace/$workspaceId/funnels/$id/edit': typeof WorkspaceWorkspaceIdFunnelsIdEditIndexRoute
  '/workspace/$workspaceId/funnels/$id/preview': typeof WorkspaceWorkspaceIdFunnelsIdPreviewIndexRoute
}
export interface FileRoutesByTo {
  '/auth/authorize': typeof AuthAuthorizeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth': typeof AuthIndexRoute
  '/f/$id': typeof funnelFIdRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdDashboardIndexRoute
  '/workspace/$workspaceId/funnels/$id/edit': typeof WorkspaceWorkspaceIdFunnelsIdEditIndexRoute
  '/workspace/$workspaceId/funnels/$id/preview': typeof WorkspaceWorkspaceIdFunnelsIdPreviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth/authorize': typeof AuthAuthorizeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/': typeof AuthIndexRoute
  '/workspace/$workspaceId/_dashboard': typeof WorkspaceWorkspaceIdDashboardRouteRouteWithChildren
  '/(funnel)/f/$id': typeof funnelFIdRoute
  '/workspace/$workspaceId/_dashboard/': typeof WorkspaceWorkspaceIdDashboardIndexRoute
  '/workspace/$workspaceId/funnels/$id/edit/': typeof WorkspaceWorkspaceIdFunnelsIdEditIndexRoute
  '/workspace/$workspaceId/funnels/$id/preview/': typeof WorkspaceWorkspaceIdFunnelsIdPreviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth/authorize'
    | '/auth/callback'
    | '/auth'
    | '/workspace/$workspaceId'
    | '/f/$id'
    | '/workspace/$workspaceId/'
    | '/workspace/$workspaceId/funnels/$id/edit'
    | '/workspace/$workspaceId/funnels/$id/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/authorize'
    | '/auth/callback'
    | '/auth'
    | '/f/$id'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/funnels/$id/edit'
    | '/workspace/$workspaceId/funnels/$id/preview'
  id:
    | '__root__'
    | '/auth/authorize'
    | '/auth/callback'
    | '/auth/'
    | '/workspace/$workspaceId/_dashboard'
    | '/(funnel)/f/$id'
    | '/workspace/$workspaceId/_dashboard/'
    | '/workspace/$workspaceId/funnels/$id/edit/'
    | '/workspace/$workspaceId/funnels/$id/preview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthAuthorizeRoute: typeof AuthAuthorizeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthIndexRoute: typeof AuthIndexRoute
  funnelFIdRoute: typeof funnelFIdRoute
  WorkspaceWorkspaceIdFunnelsIdEditIndexRoute: typeof WorkspaceWorkspaceIdFunnelsIdEditIndexRoute
  WorkspaceWorkspaceIdFunnelsIdPreviewIndexRoute: typeof WorkspaceWorkspaceIdFunnelsIdPreviewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/authorize': {
      id: '/auth/authorize'
      path: '/auth/authorize'
      fullPath: '/auth/authorize'
      preLoaderRoute: typeof AuthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(funnel)/f/$id': {
      id: '/(funnel)/f/$id'
      path: '/f/$id'
      fullPath: '/f/$id'
      preLoaderRoute: typeof funnelFIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$workspaceId/_dashboard': {
      id: '/workspace/$workspaceId/_dashboard'
      path: ''
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdDashboardRouteRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRoute
    }
    '/workspace/$workspaceId/_dashboard/': {
      id: '/workspace/$workspaceId/_dashboard/'
      path: '/'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof WorkspaceWorkspaceIdDashboardIndexRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdDashboardRouteRoute
    }
    '/workspace/$workspaceId/funnels/$id/preview/': {
      id: '/workspace/$workspaceId/funnels/$id/preview/'
      path: '/workspace/$workspaceId/funnels/$id/preview'
      fullPath: '/workspace/$workspaceId/funnels/$id/preview'
      preLoaderRoute: typeof WorkspaceWorkspaceIdFunnelsIdPreviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$workspaceId/funnels/$id/edit/': {
      id: '/workspace/$workspaceId/funnels/$id/edit/'
      path: '/workspace/$workspaceId/funnels/$id/edit'
      fullPath: '/workspace/$workspaceId/funnels/$id/edit'
      preLoaderRoute: typeof WorkspaceWorkspaceIdFunnelsIdEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthAuthorizeRoute: AuthAuthorizeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthIndexRoute: AuthIndexRoute,
  funnelFIdRoute: funnelFIdRoute,
  WorkspaceWorkspaceIdFunnelsIdEditIndexRoute:
    WorkspaceWorkspaceIdFunnelsIdEditIndexRoute,
  WorkspaceWorkspaceIdFunnelsIdPreviewIndexRoute:
    WorkspaceWorkspaceIdFunnelsIdPreviewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
